/**
 * Generates examples/example-comment.md by running the action's
 * comment-building pipeline against examples/sample-diff.patch with a
 * canned LLM response.
 *
 * Usage: `npm run examples:comment`
 *
 * It imports the same modules the bundled action uses (src/comment.ts,
 * src/inputs.ts), constructs a realistic chat-completion response, and
 * writes the resulting comment to examples/example-comment.md.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { buildCommentBody } from '../src/comment.js';
import { COMMENT_MARKER } from '../src/inputs.js';
import { splitDiffByFile } from '../src/diff.js';

const repoRoot = process.cwd();
const diffPath = path.join(repoRoot, 'examples', 'sample-diff.patch');
const outPath = path.join(repoRoot, 'examples', 'example-comment.md');

interface FileChunk {
  path: string;
  body: string;
}

const PER_FILE_SUMMARY: Record<string, string> = {
  'src/api/reports.ts': 'added Cache and logger imports; introduced in-process caching for GET /reports/:id with X-Cache HIT/MISS headers',
  'src/services/report-service.ts': 'added optional `format` field, new `exportCsv(id)` method, and `invalidateCacheFor(id)` helper',
  'src/services/csv-renderer.ts': 'new module providing `renderCsv()` and `streamCsv()` helpers with RFC-4180 escaping',
  'src/lib/cache.ts': 'new module with a generic TTL+LRU Cache class used by the reports route',
  'src/lib/logger.ts': 'new module exposing a tiny structured JSON logger (debug/info/warn/error)',
  'src/api/reports.test.ts': 'new vitest specs covering cache HIT/MISS behaviour and the exportCsv error path',
  'package.json': 'set the package to ESM via "type": "module"',
  'README.md': 'documented the new GET /reports/:id endpoint, caching semantics, and CSV export helper'
};

function buildSummary(files: FileChunk[]): string {
  const perFileLines = files
    .filter((f) => f.path in PER_FILE_SUMMARY)
    .map((f) => `File: ${f.path} — ${PER_FILE_SUMMARY[f.path]}`);

  // This mirrors what the LLM would produce from the per-file lines.
  return [
    '## Summary',
    'Introduces a 5-minute in-process cache for the report lookup endpoint, adds an RFC-4180-compliant CSV renderer with a streaming variant, and ships a tiny structured logger. The service is migrated to ESM and the README is updated to describe the new behaviour.',
    '',
    '## What changed',
    ...perFileLines.map((line) => `- ${line}`),
    '',
    '## Why',
    'Reports on the dashboard are the slowest first-paint in the app because every fetch re-parses large rows. Caching the parsed payload in-process is a cheap, zero-dependency fix that fits the existing single-instance deployment, and the CSV export unblocks the spreadsheet download flow requested by the analytics team.',
    '',
    '## Risks',
    '- In-process cache means each replica has its own view; with N replicas the effective miss rate stays roughly 1/N for the TTL window',
    '- The LRU cap of 1000 entries is silent — under heavy churn, older reports get evicted before their TTL',
    '- `invalidateCacheFor` only bumps `updated_at`; if upstream writes bypass the ORM, the cache will serve stale data for up to 5 minutes',
    '- CSV export assumes the first row defines the column set; heterogeneous rows will silently drop fields not present in `rows[0]`',
    '- Migrating to ESM is breaking for any consumer doing `require("reports-service")` — flagged in the breaking change notes',
    '',
    '## Test plan',
    '- Add round-trip CSV tests for quoted fields, embedded newlines, and Unicode characters',
    '- Verify cache HIT/MISS metrics under `npm run bench` with a cold and warm process',
    '- Smoke-test the dashboard with the cache disabled to confirm no behavioural regressions',
    '- Force a write outside the ORM and assert that the cache invalidation actually expires the entry'
  ].join('\n');
}

function main(): void {
  const diff = fs.readFileSync(diffPath, 'utf8');
  const files = splitDiffByFile(diff);
  if (files.length === 0) {
    throw new Error('Sample diff parsed to zero files — fix examples/sample-diff.patch');
  }
  const summary = buildSummary(files);
  const body = buildCommentBody(summary);

  const header = [
    '<!-- This file is generated by `npm run examples:comment`. Do not edit by hand. -->',
    '<!-- Source: scripts/generate-example-comment.ts + examples/sample-diff.patch -->',
    '',
    body
  ].join('\n');

  fs.writeFileSync(outPath, header + '\n', 'utf8');
  console.log(`Wrote ${outPath}`);
  console.log(`Marker: ${COMMENT_MARKER}`);
  console.log(`Files in sample diff: ${files.length}`);
  console.log(`Comment length: ${body.length} chars`);
}

main();
